LIBC =	ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c \
		ft_isascii.c ft_isdigit.c ft_isprint.c ft_memchr.c \
		ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c ft_strchr.c \
		ft_strdup.c ft_strlcat.c ft_strlcpy.c ft_strlen.c ft_strncmp.c \
		ft_strnstr.c ft_strrchr.c ft_tolower.c ft_toupper.c

ADDITIONAL =	ft_itoa.c ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c \
				ft_split.c ft_strmapi.c ft_strtrim.c ft_substr.c ft_striteri.c

BONUS =	ft_lstadd_back_bonus.c ft_lstadd_front_bonus.c ft_lstclear_bonus.c \
		ft_lstdelone_bonus.c ft_lstiter_bonus.c ft_lstlast_bonus.c \
		ft_lstmap_bonus.c ft_lstnew_bonus.c ft_lstsize_bonus.c

SRCS = ${LIBC} ${ADDITIONAL}

SRCSBONUS = ${BONUS}

OBJS = ${SRCS:.c=.o}

OBJSBONUS = ${SRCSBONUS:.c=.o}

CC = cc

CFLAGS = -Wall -Werror -Wextra -I ./

LIB = libft.a

all: 	${LIB}

.o: .c
	$(CC) $(CFLAGS) -zo $(SRCS) $(OBJS) -I .

bonus.o: _bonus.c
	$(CC) $(CFLAGS) -o $(SRCSBONUS) $(OBJSBONUS) -I .

bonus:	${OBJSBONUS}
		ar rsc ${LIB} ${OBJSBONUS}

${LIB}:	${OBJS}
		ar rsc ${LIB} ${OBJS}

clean:
		rm -f ${OBJSBONUS} ${OBJS}

fclean:	clean;
		rm -f ${LIB}

re:	fclean all